name: Build and Deploy Backend

on:
  push:
    # paths:
    #   - backend/**
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "24"

      - name: Install dependencies
        run: |
          cd backend
          npm ci

      - name: Build backend
        run: |
          cd backend
          npm run build

      - name: Deploy via SFTP
        uses: SamKirkland/web-deploy@v1
        with:
          target-backend: ${{ secrets.SSH_HOST }}
          remote-user: ${{ secrets.SSH_USER }}
          private-ssh-key: ${{ secrets.SSH_KEY }}
          source-path: ./backend/
          destination-path: ./backend/